# Generated by Django 5.1.1 on 2025-03-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_remove_mall_opening_date_mall_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mall_images/'),
        ),
    ]
